# Render.com Configuration
# This file configures the deployment settings for Render

services:
  - type: web
    name: smart-attendance-system
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn app:app"
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: GOOGLE_CREDENTIALS_JSON
        sync: false  # Set this manually in Render dashboard
    healthCheckPath: "/api/status"
